name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Build Docker image
      - name: Build Docker image
        run: docker build -t avinashkhadgi/nodejs-app:latest .

      # Manual Docker login
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_AUTH_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      # Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: docker push avinashkhadgi/nodejs-app:latest
